kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
---
apiVersion: v1
kind: Service
metadata:
  name: gd-mongodb
  labels:
    app: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: gd-mongodb-set
spec:
  serviceName: "gd-mongodb"
  replicas: 1
  template:
    metadata:
      labels:
        role: mongo
        environment: prod
    spec:
      nodeSelector:
        use: "general"
      terminationGracePeriodSeconds: 10
      containers:
        - name: gd-mongo
          image: mongo:3.6.17
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: gd-mongo-persistent-storage
              mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: gd-mongo-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "fast"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
            storage: 100Gi
